name: parse_args
description: A Dart package to parse command-line options simple way and in a portable style (bash, find, java, PowerShell), plus, sub-commands and sub-options
version: 0.13.3
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/parse_args/

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  file: ^7.0.0
  glob: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.23.1
  thin_logger: ^0.2.0
