name: parse_args
description: A Dart package to parse command-line options simple way and in a portable style (bash, find, java, PowerShell)
version: 0.5.2
homepage: https://aiurovet.blogspot.com/

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
