name: parse_args
description: A Dart package to parse command-line options simple way and in a portable style (bash, find, java, PowerShell), plus, sub-commands and sub-options
version: 0.10.0
homepage: https://aiurovet.blogspot.com/
repository: https://github.com/aiurovet/parse_args/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  file: ^6.1.4
  glob: ^2.1.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  thin_logger: ^0.1.3
