name: parse_args
description: A simple command-line arguments parser
version: 0.1.0
homepage: https://github.com/aiurovet/parse_args

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
